### ISSUE TITLE
Status - DAL outdated

### ISSUE THREAD

**Issue by stephanboersma** [NodeArt/angular-commerce#11]
Hi,

I am very curious to the status of this project. Will there be released a tutorial/starter kit as promised in another thread or will the DAL be update to newest firebase api/firestore? I am trying to fix it myself, however, as an amateur programmer, I do not have the skills (unfortunately).

I think this is an awesome project and I hope that you are still working on it! Thumbs up!

Best regards,

**Comment by nosovk** [comment]
There is v2 branch
https://github.com/NodeArt/angular-commerce/tree/v2
inside there is firestore iplementation
