### ISSUE TITLE
is there any live demo ?

### ISSUE THREAD

**Issue by MJahangir82** [NodeArt/angular-commerce#12]
Hello, is there any live demo? or any live site build, based on angular-commerce ?

**Comment by nosovk** [comment]
https://pond.co.ua - it's a site made on top of v1 components

**Comment by nosovk** [comment]
Currently there is a small demo of v2 version, that lives there - https://oleksmir-test.firebaseapp.com/login
(sources https://github.com/oleksmir/angular-commerce/tree/demo-app )

**Comment by MJahangir82** [comment]
Thanks, @nosovk!

**Comment by MatviiStelmakh** [comment]
all links are dead for now (

**Comment by nosovk** [comment]
https://pond-store.firebaseapp.com/ is live
but cdn is broken, will check later could it be helped
