### ISSUE TITLE
I am getting the below error .how to solve

### ISSUE THREAD

**Issue by anjutreesageorge** [NodeArt/angular-commerce#16]
ERROR in ./node_modules/@nodeart/store-components/modules/add-product-component/src/add-product.module.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /FreshFarm/node_modules/@nodeart/store-components/modules/add-product-component/src/add-product.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in thelibrary repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/FreshFarm/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:719:23)
    at plugin.done.then (/FreshFarm/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

**Comment by nosovk** [comment]
Which version of node do you use? Please use 8 or 10, not 11.

**Comment by deyvidfk** [comment]
@nosovk after your comment above I've been thinking and I make a suggestion to include in the file "package.json" the "engine" property with the version restrictions of "nodejs".

**Comment by nosovk** [comment]
@deyvidfk good idea, added engines limitation, will close an issue now
