### ISSUE TITLE
Any plans on Firestore support?

### ISSUE THREAD

**Issue by markokhman** [NodeArt/angular-commerce#17]
Hi guys
Do you have any plans on working with Firestore?

**Comment by nosovk** [comment]
Yep. We got plans on it, but currently we need customers willing to support further development

**Comment by JoeyHengst** [comment]
@nosovk can you give an indication how much is needed? Thanks.

**Comment by rubenheymans** [comment]
is this project dead? is there a live demo somewhere?

**Comment by nosovk** [comment]
currently project used in some customer products, but without financial support not going to backport those things to OSS in nearest future. Most required feature in OSS is prerender which is crucial for SEO and scalability.
