### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by prasadh13** [NodeArt/angular-commerce#3]
I understand that what you have here is an ecosystem for commerce workflow based upon angular.js. It may seem really dumb, but how do I get started with it? I want to fiddle around with it just to get it to know better.

TIA!

**Comment by nosovk** [comment]
Hello! 
At first - this project works on top of Angular 2+, not Angular 1.
Steps to install:
1. Create new firebase project - firebase.google.com
2. Launch [Flashlight](https://github.com/firebase/flashlight) with service account of yours firebase project.
3. Create new [ng-cli](https://github.com/angular/angular-cli) project 
4.  Add our components using npm - `npm i nodeart@firebase-connector` etc.

Currently we are working on a starter project to help newcomers.
If you have some time, you can contact me in skype: _nosovk_ and I will help you to make basic setup now, without starter.

**Comment by prasadh13** [comment]
Thank you for replying!
I have worked with Angular 1, not so with Angular 2 and I am unaware of the Firebase project. So there is a learning curve. Can you suggest some tutorials/material online to familiarize my with these technologies? Once I am comfortable with these, I will follow your steps.

**Comment by IvanProdaiko94** [comment]
Please read [firebase docs](https://firebase.google.com/docs/web/setup). It is quite good.
A2+
[Official docs](https://angular.io/)
[Egghead courses](https://egghead.io/technologies/angular2)
[Todd Motto articles](https://toddmotto.com/)
[Pascal Precht articles](https://blog.thoughtram.io/)

Also you can buy `ngBook2` for more advanced understanding.

**Comment by prasadh13** [comment]
Thank you!
